DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS "order";

CREATE TABLE "order" (
 id SERIAL PRIMARY KEY,
 status VARCHAR(50) DEFAULT 'pending'
);

CREATE TABLE item (
 id SERIAL PRIMARY KEY,
 order_id INTEGER REFERENCES "order"(id),
 product VARCHAR(255),
 quantity INTEGER,
 picked BOOLEAN DEFAULT FALSE
);

DROP TABLE IF EXISTS clinic_info;

CREATE TABLE clinic_info (
 id SERIAL PRIMARY KEY,
 descripcion TEXT,
 direccion VARCHAR(255),
 ubicacion_url VARCHAR(255),
 pagina_web VARCHAR(255),
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS faqs;

CREATE TABLE faqs (
 id SERIAL PRIMARY KEY,
 question VARCHAR(1024) NOT NULL,
 answer TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
