DROP TABLE IF EXISTS specialidades;

CREATE TABLE specialidades (
 id SERIAL PRIMARY KEY,
 nombre VARCHAR(255) UNIQUE NOT NULL,
 descripcion TEXT DEFAULT '',
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS clinic_info;

CREATE TABLE clinic_info (
 id SERIAL PRIMARY KEY,
 descripcion TEXT,
 direccion VARCHAR(255),
 ubicacion_url VARCHAR(255),
 pagina_web VARCHAR(255),
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS faqs;

CREATE TABLE faqs (
 id SERIAL PRIMARY KEY,
 question VARCHAR(1024) NOT NULL,
 answer TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
