CREATE TABLE IF NOT EXISTS specialidad (
 id SERIAL PRIMARY KEY,
 nombre VARCHAR(255) UNIQUE NOT NULL,
 descripcion TEXT DEFAULT '',
 atendido_por_bot BOOLEAN DEFAULT TRUE NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clinic_info (
 id SERIAL PRIMARY KEY,
 descripcion TEXT,
 direccion VARCHAR(255),
 ubicacion_url VARCHAR(255),
 pagina_web VARCHAR(255),
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faqs (
 id SERIAL PRIMARY KEY,
 question VARCHAR(1024) NOT NULL,
 answer TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
